domain_name: JLBCredit.local

safe_mode_password: "Password123!"

users:
  - AlanJohnson
  - MarkCorrigan
  - SophieChapman
  - JeffHeaney
  - Dobby
  - GerardMatthew
  - JeremyUsbourne

mhrt_users:
  - StefanStrauss

ous:
  - CEO
  - "Loan managers"
  - "IT staff"