[hyperv]
localhost ansible_connection=local

[JLBCredit-DC]
JLBCredit-DC ansible_host=10.0.0.10 dns_server=127.0.0.1

[JLBWorkstation]
JLBWorkstation ansible_host=10.0.0.30 dns_server=10.0.0.10


[all:vars]
ansible_user=Administrator
ansible_password=Password123!
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5985
ansible_winrm_scheme=http
ansible_winrm_operation_timeout_sec=60
ansible_winrm_read_timeout_sec=70