[DCs]
JLBCreditDC ansible_host=192.168.56.101 dns_server=127.0.0.1

[Workstations]
JLBWorkstation ansible_host=192.168.56.102 dns_server=192.168.56.101


[all:vars]
ansible_user=Administrator
ansible_password=Password123!
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5985
ansible_winrm_scheme=http
ansible_winrm_operation_timeout_sec=60
ansible_winrm_read_timeout_sec=70