- name: Base config on all machines
  hosts: all
  roles:
    - common

# JLBCredit forest root
- name: Create JLBCredit forest root DC
  hosts: JLBCreditDC
  roles:
    - dc_root

# Join workstations
- name: Join JLBCredit workstations
  hosts: JLBWorkstation
  roles:
    - workstation

# AD config (users, OUs, RDP)
- name: Configure AD
  hosts: JLBCreditDC
  roles:
    - ad_config
