- name: Base config on all machines
  hosts: all
  roles:
    - common

# JLBCredit forest root
- name: Create JLBCredit forest root DC
  hosts: dc_jlb_root
  roles:
    - dc_root

# Frankfurt child domain
- name: Create Frankfurt child domain
  hosts: dc_jlb_child
  roles:
    - dc_child

# MHRTFinance forest
- name: Create second forest
  hosts: dc_mhrt
  roles:
    - dc_second_forest

# Join workstations
- name: Join JLBCredit workstations
  hosts: workstations_jlb
  roles:
    - workstation

- name: Join MHRT workstations
  hosts: workstations_mhrt
  roles:
    - workstation

# AD config (users, OUs, RDP)
- name: Configure AD
  hosts: dc_jlb_root
  roles:
    - ad_config

- name: Configure Jump Box
  hosts: jumpbox
  roles:
    - workstation
    - jumpbox