# roles/dc_second_forest/tasks/main.yml
- name: Install AD DS
  ansible.windows.win_feature:
    name: AD-Domain-Services
    include_management_tools: true
    state: present

- name: Create MHRT forest
  microsoft.ad.domain:
    dns_domain_name: "{{ mhrt_domain }}"
    safe_mode_password: "{{ safe_mode_password }}"
  register: mhrt_domain_create

- name: Reboot
  ansible.windows.win_reboot:
  when: mhrt_domain_create.reboot_required | default(false)