- name: Create JLBCredit Forest
  hosts: dc1
  tasks:
    - name: Install AD DS
      win_feature:
        name: AD-Domain-Services
        state: present

    - name: Promote DC
      win_domain:
        dns_domain_name: JLBCREDIT.local
        safe_mode_password: Password123!