# roles/ad_config/tasks/main.yml
- name: Create OUs
  microsoft.ad.ou:
    name: "{{ item }}"
    path: "DC=JLBCredit,DC=local"
    state: present
  loop: "{{ ous }}"

- name: Create users
  microsoft.ad.user:
    name: "{{ item }}"
    user_principal_name: "{{ item }}@JLBCredit.local"
    password: "Passw0rd123!"
    state: present
    enabled: true
  loop: "{{ users }}"

- name: Create RDP group
  microsoft.ad.group:
    name: RDP-Access
    scope: global
    state: present

- name: Add users to RDP group
  microsoft.ad.group:
    name: RDP-Access
    members: "{{ users }}"
    state: present

- name: Add RDP group to local Remote Desktop Users
  ansible.windows.win_group_membership:
    name: "Remote Desktop Users"
    members:
      - "JLBCredit\\RDP-Access"
    state: present