# roles/ad_config/tasks/main.yml
- name: Create OUs
  microsoft.ad.ou:
    name: "{{ item }}"
    path: "DC=JLBCredit,DC=local"
    state: present
  loop: "{{ ous }}"

- name: Create users
  microsoft.ad.user:
    name: "{{ item }}"
    sam_account_name: "{{ item }}"
    upn: "{{ item }}@{{ domain_name }}"
    password: "Password123!"
    state: present
    enabled: true
  loop: "{{ users }}"

- name: Create RDP group
  microsoft.ad.group:
    name: RDP-Access
    scope: global
    state: present

- name: Add users to RDP group
  microsoft.ad.group:
    name: RDP-Access
    scope: global
    category: security
    members:
      add: "{{ rdpgang }}"
    state: present

- name: Add RDP group to local Remote Desktop Users
  ansible.windows.win_group_membership:
    name: "Remote Desktop Users"
    members:
      - "JLBCredit\\RDP-Access"
    state: present