# roles/ad_config/tasks/main.yml

- name: Create OUs
  win_domain_ou:
    name: "{{ item }}"
    path: "DC=JLBCredit,DC=local"
  loop: "{{ ous }}"

- name: Create users
  win_domain_user:
    name: "{{ item }}"
    upn: "{{ item }}@JLBCredit.local"
    password: "P@ssw0rd123!"
    state: present
  loop: "{{ users }}"

- name: Create RDP group
  win_domain_group:
    name: RDP-Access
    scope: global
    state: present

- name: Add users to RDP group
  win_domain_group_membership:
    name: RDP-Access
    members: "{{ users }}"
    state: present

- name: Add RDP group to local Remote Desktop Users
  win_group_membership:
    name: "Remote Desktop Users"
    members:
      - "JLBCredit\\RDP-Access"
    state: present
